name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hadolint Action
      uses: brpaz/hadolint-action@v1.1.0
      with:
        dockerfile: Dockerfile
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blairy/pineal:$(date +%s)
  



